### ISSUE TITLE
Add resources

### ISSUE THREAD

**Issue by advaith-unnikrishnan** [dscmbcet/dscmbcet.github.io#7]
Add more content to the resources tab. Make sure the site or content you are adding is free to use.

**Comment by julieg18** [comment]
I'm happy to help!

**Comment by advaith-unnikrishnan** [comment]
@julieg18  Glad to know that you can go ahead.

**Comment by Jethet** [comment]
I'd like to contribute as well.

**Comment by advaith-unnikrishnan** [comment]
@Jethet  yeah you can contribute.

**Comment by Jethet** [comment]
scrolling through the page there are two mentions of freecodecamp as resource. Do you want me to take one out?

**Comment by Jethet** [comment]
Another question: would you like to have the websites for Python, Django, Ruby, npm, Node.js etc etc? So the original websites you can start from, downloading a package, finding docs, doing tutorials?

**Comment by advaith-unnikrishnan** [comment]
Thanks for pointing that out you can take down the repetition of freecodecamp. You can also add the official websites of Python, Django, Ruby, etc.
